{ inputs, ... }:
{
  imports = [
    ./boot.nix
    ./emacs.nix
    ./flatpak.nix
    ./fonts.nix
    ./greetd.nix
    ./hardware.nix
    ./keyd.nix
    ./network.nix
    ./nfs.nix
    ./nh.nix
    ./packages.nix
    ./podman.nix
    ./printing.nix
    ./security.nix
    ./services.nix
    ./ssh.nix
    ./starfish.nix
    ./steam.nix
    ./stylix.nix
    ./syncthing.nix
    ./system.nix
    ./thunar.nix
    ./user.nix
    ./virtualisation.nix
    ./xserver.nix
    ./zramswap.nix
    inputs.stylix.nixosModules.stylix
  ];
}
